# Name: Chinmayi Parimal
# SAP ID: 500083359
# ROLL NO: R214220361
# Batch: 5
# Course: Container Orchestration and Infrastructure Automation
# Program: BTECH CSE (CC&VT)


# syntax=docker/dockerfile:1
FROM python:latest

WORKDIR /app

COPY . .

CMD [ "python", "client/client.py" ]